name: feature-node-js-pipeline
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ACC_ID: 367012942501
jobs:
  feature-node-js-pipeline:
    runs-on: self-hosted
    steps:
    - name: checkout code
      uses: actions/checkout@v6
    - name: list-files
      run: ls -l
      
    - name: get the version
      run: |
        #if you store it in GITHUB_ENV, you can use in other steps in same job
        echo "APP_VERSION"=${GIHHUB_SHA::9}

    - name: install dependies
      run: npm install
    - name: run unit tests
      id: unit_tests
      run: echo "run unit tests"

    - name: docker build
      id: docker_build
      run: |
        docker build -t ${{ ACC_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs/component }}:${{ APP_VERSION}} .
        docker images
        