name: feature-node-js-pipeline
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      component:
        required: true
        type: string
      environment:
        required: true
        type: string
env:
  ACC_ID: 367012942501
jobs:
  feature-node-js-pipeline:
    runs-on: self-hosted
    steps:
    - name: checkout code
      uses: actions/checkout@v6
    - name: list-files
      run: ls -l
      
    - name: get the version
      run: |
        # if you store it in GITHUB_ENV, you can use in other steps in same job
        echo "APP_VERSION"=${GITHUB_SHA::9}

    - name: install dependies
      run: npm install
    - name: run unit tests
      id: unit_tests
      run: echo "run unit tests"

    - name: Update unit test status
      if: always()
      uses: shankar-t-codes/reuseable-workflows/.github/actions/update-commit-status@main
      with:
        sha: ${{ github.sha }}
        state: ${{ steps.unit_tests.outcome }}     # success / failure / cancelled
        context: UNIT_TESTS
        description: ${{ steps.unit_tests.outcome }}

    - name: docker build
      id: docker_build
      run: |
        docker build -t ${{ env.ACC_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${{ env.APP_VERSION }} .
        docker images

    - name: Update docker build status
      if: always()
      uses: shankar-t-codes/reuseable-workflows/.github/actions/update-commit-status@main
      with:
        sha: ${{ github.sha }}
        state: ${{ steps.docker_build.outcome }}     # success / failure / cancelled
        context: DOCKER_BUILD
        description: ${{ steps.docker_build.outcome }}
